# Generated by Django 4.2 on 2023-12-08 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_apis', '0003_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='release_date',
        ),
    ]
