# Generated by Django 4.2 on 2023-12-09 05:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rest_apis', '0007_alter_movies_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='movie_poster',
            field=models.FileField(default=django.utils.timezone.now, upload_to='..media/'),
            preserve_default=False,
        ),
    ]
