# Generated by Django 5.0 on 2023-12-09 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_apis', '0008_movies_movie_poster'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
