# Generated by Django 5.0 on 2023-12-09 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_apis', '0009_delete_movies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=256)),
                ('movie_poster', models.FileField(upload_to='..media/')),
                ('release_date', models.DateField()),
                ('duration', models.DurationField()),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MaxValueValidator(limit_value=10)])),
                ('language', models.CharField(max_length=256)),
                ('genre', models.CharField(max_length=256)),
                ('cbc', models.CharField(max_length=256)),
                ('movie_description', models.TextField(max_length=2000)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('modified_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
