# Generated by Django 5.0 on 2023-12-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_apis', '0011_customuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theater_name', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(default=0)),
                ('cancellation', models.BooleanField(default=False)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('modified_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
