# Generated by Django 4.2 on 2023-12-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_apis', '0014_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie_name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='theater',
            name='theater_name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
