# Generated by Django 4.2 on 2023-12-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_apis', '0015_alter_movies_movie_name_alter_theater_theater_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='avaliable_seates',
            field=models.IntegerField(default=0),
        ),
    ]
